### PR TITLE
Fix compilation error.

### PR DESCRIPTION
**Pull request by paddycarver**
go-getter updated outside of semver and created a compilation error. Fix
the error.

### CODE REVIEW

**Comment by kmoe** [comment]
terraform-plugin-test compiles fine with go-getter v1.4.0 - what error are you getting?

**Review by kmoe — APPROVED** [review]
